# Generated by Django 5.2.12 on 2026-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_ayuda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicio_usuario",
            name="fecha_vencimiento",
        ),
        migrations.AddField(
            model_name="servicio_usuario",
            name="dia_vencimiento",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Día del mes de vencimiento (1-31)"
            ),
        ),
    ]
